### ISSUE TITLE
output path array variables appropriately

### ISSUE THREAD

**Issue by domanchi** [Yelp/fuzz-lightyear#22]
Let's say we have the following specification:

```
paths:
  /businesses/{ids}/info:
    get:
      parameters:
        - name: ids
          in: path
          required: true
          type: array
          collectionFormat: csv
          items:
            type: integer
```

Currently, when we output the [reproducible `curl` request](https://github.com/Yelp/fuzz-lightyear/blob/master/fuzz_lightyear/request.py#L60), it would look something like:

```
/businesses/[1,2]/info
```

rather than the expected:

```
/businesses/1%2C2/info
```

Let's fix this for better reproducibility.
