### ISSUE TITLE
support file uploads

### ISSUE THREAD

**Issue by domanchi** [Yelp/fuzz-lightyear#4]
### Summary

In the petstore example, `/pet/{petId}/uploadImage` accepts a file in the formData.

```
/pet/{petId}/uploadImage:
  post:
    parameters:
    - name: "file"
      in: "formData"
      description: "file to upload"
      required: false
      type: "file"
```

We don't currently support this. Maybe we should?
